# Site settings
name: Yang Wang
title: Yang Wang | Machine Learning and Natural Language Processing Researcher
description: Researcher focused on Natural Language Processing and Applied Mathematics.
url: https://yangwang825.github.io/
baseurl: ''
email: yangwang4work@gmail.com
cover: https://yangwang825.github.io/img/og.png
logo: '' # https://yangwang825.github.io/img/emojis/technologist.png
resume: https://yangwang825.github.io/resume.pdf
social:
  - title: email
    url: mailto:yangwang4work@gmail.com
  # - title: twitter
  #   url: https://twitter.com/bchiang7
  # - title: instagram
  #   url: https://instagram.com/bchiang7
  # - title: codepen
  #   url: http://codepen.io/bchiang7
  - title: github
    url: https://github.com/yangwang825
  - title: linkedin
    url: https://www.linkedin.com/in/yang-wang-sheffield/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
